# Generated by Django 4.2.7 on 2025-08-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountcategory",
            name="code",
            field=models.CharField(max_length=100, verbose_name="Category Code"),
        ),
    ]
