# Generated by Django 4.2.7 on 2025-08-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_alter_accountcategory_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_reversal",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this transaction is a reversal of another.",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="The original transaction that this transaction reverses.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversal_transaction",
                to="accounting.transaction",
            ),
        ),
    ]
