# Generated by Django 4.2.7 on 2025-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0004_update_account_type_normal_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttype",
            name="normal_balance",
            field=models.CharField(
                choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                max_length=10,
                verbose_name="Normal Balance",
            ),
        ),
    ]
